@startuml
采购员填写供应商信息 -> 供应商填写模板: 发送邀请链接给当前供应商
供应商填写模板 -> 准入评分 : 系统/人工 打分
准入评分 ->O 供应商信息录入 : 评分通过
准入评分 ->X 供应商信息录入 : 评分不通过 结束流程
供应商信息录入 -> 供应商认证 : 提交
供应商认证 -> 模板角色评分
模板角色评分 -> 评分结果审批
评分结果审批 ->O 待入库
评分结果审批 ->X 结束流程
待入库 -> 入库 : 提交
@enduml
