@startuml
start
:采购录入供应商信息;
:发送邀请邮件;
if (供应商填写准入模板) then (不通过)
:结束流程;
end
else(通过)
:供应商信息录入;
:提交;
:供应商认证;
:发送邮件;
:各角色评分;
if (认证审批) then (不通过)
:结束流程;
end
else(通过)
:待入库;
:入库提交;
:ptp seahorse入库;
end
@enduml